# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('subtitle', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('isbn', models.IntegerField()),
                ('barcode', models.CharField(default='', max_length=20)),
                ('has_own_barcode', models.BooleanField(default=False)),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='biblio.AuthorCombination')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_books', to='biblio.Publisher'),
        ),
    ]
