# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20171119_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.AddField(
            model_name='publisher',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publisher',
            name='shown_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='authorcombination',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
